x-countly-image: &countly-image
  image: ${COUNTLY_LOCAL_IMAGE:-soda-countly:local}

x-countly-environment: &countly-environment
  COUNTLY_PLUGINS: mobile,web,desktop,plugins,density,locale,browser,sources,views,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards,sdk,data-manager
  COUNTLY_CONFIG_HOSTNAME: ${COUNTLY_CONFIG_HOSTNAME:-localhost}
  COUNTLY_CONFIG__MONGODB: "${COUNTLY_MONGODB_URI:-mongodb://countly:Fengxiangbiao%40123@mongoreplicab7e0673b0fc70.mongodb.cn-shanghai.ivolces.com:3717,mongoreplicab7e0673b0fc71.mongodb.cn-shanghai.ivolces.com:3717/countly?authSource=admin&replicaSet=rs-mongo-replica-b7e0673b0fc7&retryWrites=true}"
  COUNTLY_CONFIG__FILESTORAGE: gridfs
  COUNTLY_CONFIG_API_API_HOST: 0.0.0.0
  COUNTLY_CONFIG_FRONTEND_WEB_HOST: 0.0.0.0
  NODE_OPTIONS: --max-old-space-size=2048
  INSIDE_DOCKER: "1"

networks:
  countly:

services:
  countly-api:
    <<: *countly-image
    command: /opt/countly/bin/docker/cmd.sh
    environment:
      <<: *countly-environment
      COUNTLY_CONTAINER: api
      COUNTLY_CONFIG_API_API_WORKERS: "4"
    networks:
      countly:

  countly-frontend:
    <<: *countly-image
    command: /opt/countly/bin/docker/cmd.sh
    environment:
      <<: *countly-environment
      COUNTLY_CONTAINER: frontend
    networks:
      countly:

  nginx:
    image: 'bitnami/nginx'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './bin/docker/nginx.server.conf:/opt/bitnami/nginx/conf/server_blocks/countly.conf:ro'
      - './certs:/opt/bitnami/nginx/certs:ro'
      - '/var/www/certbot:/var/www/certbot:ro'
    networks:
      countly:
    depends_on:
      - countly-api
      - countly-frontend
